# Generated by Django 4.1.7 on 2023-03-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restifyuser',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile_pictures/'),
        ),
    ]
