# Generated by Django 4.1.7 on 2023-03-11 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('property_images', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(max_length=200)),
                ('available_dates', models.JSONField(default=list)),
                ('guest_capacity', models.PositiveIntegerField()),
                ('amenities', models.CharField(choices=[('pool', 'Pool'), ('hottub', 'Hottub'), ('gym', 'Gym'), ('parking', 'Parking'), ('oceanview', 'OceanView'), ('restaurant', 'Restaurant')], default='', max_length=20)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
