# Generated by Django 4.1.7 on 2023-03-12 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('property_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('property_images', models.JSONField(blank=True, default=list, null=True)),
                ('default_price', models.PositiveIntegerField()),
                ('location', models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NT', 'Northwest Territories'), ('NS', 'Nova Scotia'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], max_length=2)),
                ('available_dates', models.JSONField(default=list)),
                ('guest_capacity', models.PositiveIntegerField()),
                ('amenity', multiselectfield.db.fields.MultiSelectField(choices=[('pool', 'Pool'), ('hottub', 'Hottub'), ('gym', 'Gym'), ('parking', 'Parking'), ('oceanview', 'OceanView'), ('restaurant', 'Restaurant'), ('wifi', 'Wifi'), ('tv', 'TV'), ('kitchen', 'Kitchen'), ('laundry', 'Laundry'), ('pets', 'Pets'), ('smoking', 'Smoking'), ('airconditioning', 'AirConditioning'), ('heating', 'Heating')], max_length=255)),
                ('rating', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
