# Generated by Django 4.1.7 on 2023-03-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.CharField(choices=[('pool', 'Pool'), ('hottub', 'Hottub'), ('gym', 'Gym'), ('parking', 'Parking'), ('oceanview', 'OceanView'), ('restaurant', 'Restaurant')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='available_dates',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(),
        ),
    ]
