# Generated by Django 4.1.7 on 2023-03-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_amenities_property_available_dates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='name',
            new_name='property_name',
        ),
        migrations.AlterField(
            model_name='property',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
