# Generated by Django 4.1.7 on 2023-03-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_rename_name_property_property_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
