# Generated by Django 4.1.5 on 2023-03-09 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('number_of_guests', models.PositiveIntegerField(default=0)),
                ('reservation_status', models.CharField(choices=[('pending', 'Pending'), ('denied', 'Denied'), ('expired', 'Expired'), ('approved', 'Approved'), ('canceled', 'Canceled'), ('terminated', 'Terminated'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to=settings.AUTH_USER_MODEL)),
                ('liable_guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='property.property')),
            ],
        ),
    ]
