# Generated by Django 4.1.7 on 2023-03-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('number_of_guests', models.PositiveIntegerField(default=0)),
                ('_reservation_status', models.CharField(choices=[('pending', 'Pending'), ('denied', 'Denied'), ('expired', 'Expired'), ('approved', 'Approved'), ('canceled', 'Canceled'), ('terminated', 'Terminated'), ('completed', 'Completed')], db_column='reservation_status', default='pending', max_length=25)),
            ],
            options={
                'ordering': ['check_in'],
            },
        ),
    ]
