# Generated by Django 4.1.7 on 2023-03-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('denied', 'Denied'), ('expired', 'Expired'), ('approved', 'Approved'), ('canceled', 'Canceled'), ('terminated', 'Terminated'), ('completed', 'Completed')], default='pending', max_length=25),
        ),
    ]
