# Generated by Django 4.1.7 on 2023-03-10 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_property_images'),
        ('reservation', '0004_alter_reservation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='property.property'),
        ),
    ]
