# Generated by Django 4.1.7 on 2023-03-10 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_reservation_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='place',
        ),
    ]
