# Generated by Django 4.1.7 on 2023-03-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_remove_reservation_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('denied', 'Denied'), ('expired', 'Expired'), ('approved', 'Approved'), ('canceled', 'Canceled'), ('terminated', 'Terminated'), ('completed', 'Completed')], db_column='reservation_status', default='pending', max_length=25),
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_status',
            new_name='_reservation_status',
        ),
    ]
