# Generated by Django 4.1.5 on 2023-03-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_guestreplycomment_hostreplycomment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestcomment',
            name='reply',
        ),
    ]
