# Generated by Django 4.1.7 on 2023-03-10 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_remove_guestcomment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='guest_comment',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comment.guestcomment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='property_comment',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comment.propertycomment'),
        ),
        migrations.AlterField(
            model_name='hostreplycomment',
            name='reply',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comment.guestreplycomment'),
        ),
        migrations.AlterField(
            model_name='propertycomment',
            name='reply',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comment.hostreplycomment'),
        ),
    ]
