# Generated by Django 4.1.7 on 2023-03-11 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0004_property_property_images'),
        ('comment', '0004_alter_comment_guest_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestPropertyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GuestPropertyReplyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HostPropertyReplyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('reply', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comment.guestpropertycomment')),
            ],
        ),
        migrations.RemoveField(
            model_name='hostreplycomment',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='propertycomment',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='guest_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='property_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='property.property'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GuestComment',
        ),
        migrations.DeleteModel(
            name='GuestReplyComment',
        ),
        migrations.DeleteModel(
            name='HostReplyComment',
        ),
        migrations.DeleteModel(
            name='PropertyComment',
        ),
        migrations.AddField(
            model_name='guestpropertycomment',
            name='reply',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comment.hostpropertyreplycomment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='guest_property_comment',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comment.guestpropertycomment'),
        ),
    ]
