# Generated by Django 4.1.7 on 2023-03-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_guestpropertycomment_guestpropertyreplycomment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='guest_property_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='enter comment'),
        ),
    ]
