# Generated by Django 4.1.7 on 2023-03-11 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_remove_comment_guest_property_comment_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
