# Generated by Django 4.1.7 on 2023-03-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reservation', 'Reservation'), ('cancellation', 'Cancellation'), ('approval', 'Approval')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_type',
            field=models.CharField(choices=[('host', 'Host'), ('guest', 'Guest')], default='guest', max_length=10),
        ),
    ]
