# Generated by Django 4.1.7 on 2023-03-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_remove_notification_recipient_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reservation', 'Reservation'), ('cancellation', 'Cancellation'), ('approval', 'Approval')], default='reservation', max_length=20),
        ),
    ]
